@baseUrl = http://localhost:4000
@contentType = application/json


###
# 1) Reg
POST {{baseUrl}}/users/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "jwt_user@test.ru",
  "name": "JWT User",
  "password": "123456",
  "type": "обычный"
}

###
# 2) Login
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "jwt_user@test.ru",
  "password": "123456"
}

###
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGFjMDFlNTM2YmNkNzk5OTkzYjA2NiIsImVtYWlsIjoiand0X3VzZXJAdGVzdC5ydSIsIm5hbWUiOiJKV1QgVXNlciIsImlhdCI6MTc2NjUwNjUzMiwiZXhwIjoxNzY2Njc5MzMyfQ.4UMK-pkBW5BDiFjQfZE2QzsXrCvqIKwO1wbQNEzX8Qg

# Favorites without token
GET {{baseUrl}}/offers/favorites HTTP/1.1

###
# Logout without token
POST {{baseUrl}}/users/logout HTTP/1.1

###
# Favorites with token
GET {{baseUrl}}/offers/favorites HTTP/1.1
Authorization: {{token}}

###
# Logout with token
POST {{baseUrl}}/users/logout HTTP/1.1
Authorization: {{token}}

###
# Offers list WITHOUT token
GET {{baseUrl}}/offers HTTP/1.1

###
# Offers list WITH token
GET {{baseUrl}}/offers HTTP/1.1
Authorization: {{token}}

###
@offerId = 68f52a93be83f0b6f93f58ba

###
# Create comment WITHOUT token
POST {{baseUrl}}/comments/{{offerId}} HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "Unauthorized comment should fail",
  "rating": 3
}

###
# Create comment WITH token
POST {{baseUrl}}/comments/{{offerId}} HTTP/1.1
Authorization: {{token}}
Content-Type: {{contentType}}

{
  "text": "Nice place, would stay again (JWT).",
  "rating": 5
}

###
# List comments for offer
GET {{baseUrl}}/comments/{{offerId}} HTTP/1.1

###
# Upload avatar WITH token
POST {{baseUrl}}/users/avatar HTTP/1.1
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./mocks/avatar.jpg
--WebAppBoundary--

### Healthcheck
GET {{baseUrl}}/ HTTP/1.1

###
@favoriteOfferId = 68f52a93be83f0b6f93f58ba

###
# Add to favorites
POST {{baseUrl}}/offers/favorites/{{favoriteOfferId}} HTTP/1.1
Authorization: {{token}}

###
# Check favorites list includes offer
GET {{baseUrl}}/offers/favorites HTTP/1.1
Authorization: {{token}}

###
# Remove from favorites
DELETE {{baseUrl}}/offers/favorites/{{favoriteOfferId}} HTTP/1.1
Authorization: {{token}}

